---
# Enable or disable the installation of the osquery debug packages.
osquery_debug_packages_install: false

osquery_upload_packs:
  - osquery-snapshots-pack
  - osquery-monitoring2-pack

osquery_packs:
  - "osquery-monitoring"
  - "incident-response"
  - "it-compliance"
  - "ossec-rootkit"
  - "vuln-management"
  - "hardware-monitoring"
  - "osquery-snapshots-pack"
  - "osquery-monitoring2-pack"

# osquery_flags:
#   - '--enroll_secret_path=/etc/osquery/osquery_enroll_secret'
#   - '--tls_server_certs=/etc/osquery/kolide.crt'
#   - '--tls_hostname=acme.kolide.co'
#   - '--host_identifier=hostname'
#   - '--enroll_tls_endpoint=/api/v1/osquery/enroll'
#   - '--config_plugin=tls'
#   - '--config_tls_endpoint=/api/v1/osquery/config'
#   - '--config_tls_refresh=10'
#   - '--disable_distributed=false'
#   - '--distributed_plugin=tls'
#   - '--distributed_interval=10'
#   - '--distributed_tls_max_attempts=3'
#   - '--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read'
#   - '--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write'
#   - '--logger_plugin=tls'
#   - '--logger_tls_endpoint=/api/v1/osquery/log'
#   - '--logger_tls_period=10'
osquery_flags: []

## Take care if using a lot /tmp. can trigger
## 'Expiring events for subscriber: file_events (overflowed limit 1000)'
## => losing many queries results (fim or not)
osquery_fim_filepaths:
  - name: homes_sshdir
    list:
      - "/root/.ssh/%%"
      - "/home/%/.ssh/%%"
      - "/home/lib/%/.ssh/%%"
  - name: etc
    list:
      - "/etc/%%"
  - name: bin
    list:
      - "/bin/%%"
      - "/sbin/%%"
      - "/usr/bin/%%"
      - "/usr/sbin/%%"
      - "/usr/local/bin/%%"
      - "/usr/local/sbin/%%"
      - "/opt/bin/%%"
      - "/opt/sbin/%%"
  - name: webroot
    list:
      - "/var/www/%%"

osquery_fim_excludepaths:
  - name: tmp
    list:
      - /tmp/too_many_events/

## queries snapshots: 1/week
## Max interval 1/w: https://github.com/theopolis/osquery/commit/b76dee8a1fddccb500bc4a058daa1b39083b9dbb
osquery_snapshot_interval: 604800
osquery_snapshot_interval2: 604800

osquery_options:
  options:
    ## Splay the scheduled interval for queries.
    ## This is very helpful to prevent system performance impact when scheduling
    ## large numbers of queries that run a smaller or similar intervals.
    schedule_splay_percent: 10
    ## Clear events from the osquery backing store after a number of seconds.
    events_expiry: 3600
    ## Enable debug or verbose debug output when logging.
    verbose: false
    ## The number of threads for concurrent query schedule execution.
    worker_threads: 2
    ## Enable schedule profiling, this will fill in averages and totals for
    ## system/user CPU time and memory for every query in the schedule.
    ## Add a query: "select * from osquery_schedule" to record the performances.
    enable_monitor: true
    logger_snapshot_event_type: true
  ## Define a schedule of queries:
  schedule:
    ## This is a simple example query that outputs basic system information.
    system_info:
      ## The exact query to run.
      query: "SELECT hostname, cpu_brand, physical_memory FROM system_info;"
      ## The interval in seconds to run this query, not an exact interval.
      interval: 3600
    fim:
      query: "select * from file_events;"
      removed: false
      ## fim query interval
      interval: 900
  ## Decorators are normal queries that append data to every query.
  decorators:
    load:
      - "SELECT uuid AS host_uuid FROM system_info;"
      - "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
