---
# Copyright 2019, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

traefik_analyzer_service_state: restarted

# traefik_destinations:
#   env_name:
#     proto: http
#     port: 9200
#     bind: 127.0.0.1
#     servers:
#       - name: server1
#         address: 10.0.0.1
#         weight: 1
#       - name: server2
#         address: 10.0.0.2
#         weight: 2
traefik_destinations: {}

# Path to the docker socket on a local or remote system running traefik
traefik_docker_socket: "unix://var/run/docker.sock"

traffic_dashboard_bind: "{{ ansible_default_ipv4['address'] }}"

traefik_dashboard_port: "8090"

traefik_dashboard_enabled: false

# Set basic authentication users and passwords into a basic auth file.
# This is optional and will only be created if user defined.
# traefik_basic_auth_users:
#   traefik: secrete
traefik_basic_auth_users: {}

traefik_basic_auth_file: /var/lib/traefik/traefik.secret
