---
osquery_required_packages:
  - apt-transport-https
  - dirmngr
  - logrotate

osquery_packages:
  - osquery
  - rsyslog

osquery_debug_packages:
  - osquery-dbg

_osquery_repository: "{{ osquery_repository | default('deb [arch=amd64] https://pkg.osquery.io/deb deb main') }}"
_osquery_repositorykey: "{{ osquery_repositorykey | default('1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B') }}"

varlog_group: syslog
varlog_mode: '0775'
