---
osquery_required_packages:
  - logrotate

osquery_packages:
  - osquery
  - rsyslog

osquery_debug_packages:
  - osquery-debuginfo

_osquery_repository: "{{ osquery_repository | default('https://pkg.osquery.io/rpm/osquery-s3-rpm.repo') }}"
_osquery_repositorykey: "{{ osquery_repositorykey | default('https://pkg.osquery.io/rpm/GPG') }}"

varlog_group: root
varlog_mode: '0755'
