---
- name: Ensure dirmngr is present for apt-key
  package:
    name: "{{ osquery_required_packages }}"
    state: present

- name: Download osquery APT key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ _osquery_repositorykey }}"
    state: present
  tags:
    - osquery

- name: Configure osquery APT repository
  become: yes
  apt_repository:
    repo: "{{ _osquery_repository }}"
    state: present
  tags:
    - osquery
